# Generated by Django 4.2.1 on 2023-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Chat last update date and time"
            ),
        ),
    ]
